### ISSUE TITLE
Issue with links when path set to /

### ISSUE THREAD

**Issue by navidnadali** [LuminFire/Nova-Relationships-Link-List#1]
Hi @andrewminion-luminfire , Great work and thanks for the package!

Quick issue, When nova.path is set to '/' as follow:

![image](https://user-images.githubusercontent.com/2290350/105917137-e19cb000-6029-11eb-81a4-3e7b316b5740.png)

This results in a double // at the start of the URL breaking the relative path and resulting in 404's when clicked: 

HTML: 

![image](https://user-images.githubusercontent.com/2290350/105917386-26c0e200-602a-11eb-9ccc-a3a5af454b9a.png)

Browser result:

![image](https://user-images.githubusercontent.com/2290350/105917517-4fe17280-602a-11eb-8b0e-1904dc1a72e6.png)

Thanks!

**Comment by navidnadali** [comment]
PR submitted.

**Comment by andrewminion-luminfire** [comment]
@navidnadali Thanks for the report and the PR! Could you try updating to 0.3.0? I think [this change](https://github.com/LuminFire/Nova-Relationships-Link-List/commit/e8ec418ac106de1ed47c23ace3fb4447961156dc) fixes the error.

**Comment by navidnadali** [comment]
Perfect thanks @andrewminion-luminfire confirmed fixed.
